<?xml version="1.0" encoding="utf-8"?><Database Name="KhachSan" Class="KhachSanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=KhachSan;User ID=sa" SettingsObjectName="BussinessLayer.Properties.Settings" SettingsPropertyName="KhachSanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietDatPhong" Member="ChiTietDatPhongs">
    <Type Name="ChiTietDatPhong">
      <Column Name="MaChiTietDatPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDatPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNgayO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TinhNang" Member="TinhNangs">
    <Type Name="TinhNang">
      <Column Name="MaTinhNang" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SapXep" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Decription" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IsGroup" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Parent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Menu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tips" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CongTy" Member="CongTies">
    <Type Name="CongTy">
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCongTy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CongTy_DonVi" Member="DonVis" ThisKey="MaCongTy" OtherKey="MaCongTy" Type="DonVi" />
      <Association Name="CongTy_NhanVien" Member="NhanViens" ThisKey="MaCongTy" OtherKey="MaCongTy" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.CongTy_DonVi" Member="CongTy_DonVis">
    <Type Name="CongTy_DonVi">
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDonVi" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCongTy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenDonVi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatPhong" Member="DatPhongs">
    <Type Name="DatPhong">
      <Column Name="MaDatPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDatPhong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTraPhong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoNguoiO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaDonVi" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TheoDoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNhanVienCapNhat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhachHang_DatPhong" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_DatPhong" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatPhong_SanPham" Member="DatPhong_SanPhams">
    <Type Name="DatPhong_SanPham">
      <Column Name="MaChiTietSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDatPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChiTietDatPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonVi" Member="DonVis">
    <Type Name="DonVi">
      <Column Name="MaDonVi" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDonVi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DonVi_NhanVien" Member="NhanViens" ThisKey="MaDonVi" OtherKey="MaDonVi" Type="NhanVien" />
      <Association Name="CongTy_DonVi" Member="CongTy" ThisKey="MaCongTy" OtherKey="MaCongTy" Type="CongTy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Nam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KhachHang_DatPhong" Member="DatPhongs" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="DatPhong" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="MaLoaiPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiPhong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoNguoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoGiuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaDonVi" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KhoaTaiKhoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NhanVien_DatPhong" Member="DatPhongs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="DatPhong" />
      <Association Name="CongTy_NhanVien" Member="CongTy" ThisKey="MaCongTy" OtherKey="MaCongTy" Type="CongTy" IsForeignKey="true" />
      <Association Name="DonVi_NhanVien" Member="DonVi" ThisKey="MaDonVi" OtherKey="MaDonVi" Type="DonVi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhomQuyen" Member="NhomQuyens">
    <Type Name="NhomQuyen">
      <Column Name="Nhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaTang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Phong_Phong_ThietBi" Member="Phong_ThietBis" ThisKey="MaPhong" OtherKey="MaPhong" Type="Phong_ThietBi" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="LoaiPhong" IsForeignKey="true" />
      <Association Name="Tang_Phong" Member="Tang" ThisKey="MaTang" OtherKey="MaTang" Type="Tang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong_ThietBi" Member="Phong_ThietBis">
    <Type Name="Phong_ThietBi">
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThietBi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phong_Phong_ThietBi" Member="Phong" ThisKey="MaPhong" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
      <Association Name="ThietBi_Phong_ThietBi" Member="ThietBi" ThisKey="MaThietBi" OtherKey="MaThietBi" Type="ThietBi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen" Member="Quyens">
    <Type Name="Quyen">
      <Column Name="MaTinhNang" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quyen" Member="Quyen1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tang" Member="Tangs">
    <Type Name="Tang">
      <Column Name="MaTang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tang_Phong" Member="Phongs" ThisKey="MaTang" OtherKey="MaTang" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.ThietBi" Member="ThietBis">
    <Type Name="ThietBi">
      <Column Name="MaThietBi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThietBi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ThietBi_Phong_ThietBi" Member="Phong_ThietBis" ThisKey="MaThietBi" OtherKey="MaThietBi" Type="Phong_ThietBi" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVienKhongTrongNhom" Member="NhanVienKhongTrongNhoms">
    <Type Name="NhanVienKhongTrongNhom">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaDonVi" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KhoaTaiKhoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuyenTinhNang" Member="QuyenTinhNangs">
    <Type Name="QuyenTinhNang">
      <Column Name="MaTinhNang" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Decription" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IsGroup" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Parent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SapXep" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quyen" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVienTrongNhom" Member="NhanVienTrongNhoms">
    <Type Name="NhanVienTrongNhom">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaDonVi" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KhoaTaiKhoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.PHIEU_DATPHONG" Method="PHIEU_DATPHONG">
    <Parameter Name="MADATPHONG" Parameter="mADATPHONG" Type="System.Int32" DbType="Int" />
    <ElementType Name="PHIEU_DATPHONGResult">
      <Column Name="MaDatPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayDatPhong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTraPhong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoNguoiO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaDonVi" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoNgayO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dp_DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dp_ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaChiTietSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sp_SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sp_DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sp_ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PHIEU_DATPHONG" Method="PHIEU_DATPHONG1">
    <Parameter Name="MADATPHONG" Parameter="mADATPHONG" Type="System.Int32" DbType="Int" />
    <ElementType Name="PHIEU_DATPHONGResult1">
      <Column Name="MaDatPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayDatPhong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTraPhong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoNguoiO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCongTy" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaDonVi" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoNgayO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dp_DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dp_ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaChiTietSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sp_SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sp_DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sp_ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>